---
- name: include
  hosts: all
  become: yes

  vars:
        mytext: "privet Dima"

  tasks:
  - include: create_folder.yml
  - include: create_file.yml

  - name: reboot my server
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: wait my server
    wait_for:
          hosts: "{{ inventory_hostname }}"
          state: started
          delay: 5
          timeout: 40
  delegate_to: 172.20.13.142
 
