---
- name: install apache to my all server
  hosts: "{{ MYHOSTS }}"
  become: yes

  vars:
    sorce_folder: /etc/ansible
    dist_folder: /var/www/html

  tasks:
  - name: install apache web server
    apt: name=apache2 state=latest

  tasks:
  - name: copy my homepage to server
    template: src={{ sorce_folder }}/index.j2 dest={{ dist_folder }}/index.html mode=0555
    notify: restart Apache

  - name: start webserver and make it enable on boot
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
