---
# tasks file for deploy_apache_web
  - name: install apache web server
    apt: name=apache2 state=latest

  - name: copy my homepage to server
    copy: src={{ item }} dest={{ destin_folder }} mode=0555
    loop: 
      - "index.html"
    notify: restart Apache

  - name: start webserver and make it enable on boot
    service: name=apache2 state=started enabled=yes
